image: docker
services:
  - docker:dind

stages:
  - test

test:
  stage: test
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose up --abort-on-container-exit
