image: docker
services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker-compose up --abort-on-container-exit

build:
  stage: build
  before_script:
    - docker build . -t githome-build-toolchain
  script:
    - docker run --rm githome-build-toolchain /usr/bin/make raw-deb
  when: manual
  artifacts:
      paths:
        - "rel/*.deb"
