image: ubuntu:bionic

services:
  - docker:latest

#variables:
#  DOCKER_HOST: tcp://localhost:2375


before_script:
  - apt update
  - apt install npm make curl gnupg build-essential lsb-release -y
  - curl -O https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - dpkg -i erlang-solutions_1.0_all.deb && apt install -f
  - apt update && apt upgrade -y
  - apt install esl-erlang elixir -y
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force

stages:
  - init
  - compile
  - test
  - build

prepare:
  stage: init
  script:
    - make raw-init

compile:
  stage: compile
  script:
    - make raw-compile
  cache: &build-cache
    key: ${CI_COMMIT_SHA}-build
    paths:
      - "_build/"

test:
  stage: test
  script:
    - make raw-test
  cache: *build-cache

build:
  stage: build
  script:
    - make raw-init
    - make raw-deb
  artifacts:
      paths:
        - "rel/*.deb"
