image: docker
services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - docker-compose up --abort-on-container-exit

build:
  stage: build
  variables:
    MIX_ENV: prod
  before_script:
    - apk add make
    - make tc
  script:
    - make init
    - make deb
  when: manual
  artifacts:
      paths:
        - "rel/*.deb"
