image: ubuntu:bionic

services:
  - docker:latest

#variables:
#  DOCKER_HOST: tcp://localhost:2375


before_script:
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - apt update
  - apt install make
#  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
#  - dpkg -i erlang-solutions_1.0_all.deb
#  - apt update
#  - apt install esl-erlang elixir -y
#  - apt-get update
#  - apt-get install apt-transport-https ca-certificates curl software-properties-common -y
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
#  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - apt-get update
#  - apt-get install docker-ce -y

stages:
  - toolchain
  - compile
  - test
  - build

tc:
  stage: toolchain
  script:
    - docker run hello-world

compile:
  stage: compile
  script:
    - make compile
  cache: &build-cache
    key: ${CI_COMMIT_SHA}-build
    paths:
      - "_build/"

test:
  stage: test
  script:
    - make test
  cache: *build-cache

build:
  stage: build
  script:
    - make deb
  artifacts:
      paths:
        - "rel/*.deb"
