version: '3'
services:
  web:
    build:
      context: "docker"
      dockerfile: "elixir.Dockerfile"
    command: "mix test"
    working_dir: "/home/githome/app"
    environment:
      MIX_ENV: test
      MIX_DEBUG: 1
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
    volumes:
      - .:/home/githome/app
    user: githome
    links:
      - db:db
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: githome_test
      MYSQL_ROOT_PASSWORD: root
