#!/bin/bash

. /usr/share/debconf/confmodule

USER="githome"
GROUP="githome"

Set_DB_Connection_config() {
    db_get githome/mysql_githome_login
    GITHOME_USER_MYSQL="${RET}"
    sed -i -e "s/LOGIN=.*/LOGIN=\"${GITHOME_USER_MYSQL}\"/g" /etc/githome/mysql.conf
    db_get githome/mysql_githome_password
    githome_PASSWORD_MYSQL="${RET}"
    sed -i -e "s/PASSWORD=.*/PASSWORD=\"${githome_PASSWORD_MYSQL}\"/g" /etc/githome/mysql.conf
    db_get githome/mysql_host
    HOST_MYSQL="${RET}"
    sed -i -e "s/HOST=.*/HOST=\"${HOST_MYSQL}\"/g" /etc/githome/mysql.conf
    DB_NAME="githome"
    sed -i -e "s/DB_NAME=.*/DB_NAME=\"${DB_NAME}\"/g" /etc/githome/mysql.conf
}

case "${1}" in
    configure|reconfigure)
        # Не обрабатываем подкаталоги, т.к. база может быть весьма объемной и эта операция может занять десятки минут
#        install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /var/cache/githome-simens-dhcp.conf/githome-simens-dhcp.conf-githome-simens-dhcp.conf-githome-core #В будущем для кэширования
#        install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /var/log/ecss/githome
#         install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /usr/lib/githome/db-deployment/deploy-database.sh
#         install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /etc/githome
#        install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /usr/lib/ecss/githome/dnsmasq.d
#        install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /var/lib/ecss/githome
#        chmod u+rw,g+rw,o+r -R /var/lib/ecss/githome
#        install -d -o ${USER} -g ${GROUP} -m ug+rwx,o+rx /etc/ecss/githome
#        chown ${USER}:${GROUP} /usr/lib/ecss/githome/lua/*.lua
#        chmod u+srwx,g+rwsx,o+s /usr/lib/ecss/githome/lua/*.lua
        chown ${USER}:${GROUP} /usr/lib/githome/*
        chmod u+rwx,g+rx,o+r /usr/lib/githome/*
        chown ${USER}:${GROUP} /opt/githome/*
        chmod u+rwx,g+rx,o+r /opt/githome/*
        chown ${USER}:${GROUP} /var/lib/githome/*
        chmod u+rwx,g+rx,o+r /var/lib/githome/
        chown ${USER}:${GROUP} /etc/githome/*
        chmod u+rwx,g+rx,o+r /etc/githome/*
#        chown ${USER}:${GROUP} /etc/nginx/sites-available/githome*
#        chmod u+rwx,g+rx,o+r /etc/nginx/sites-available/githome*
#        chown ${USER}:${GROUP} /usr/lib/ecss/githome/dnsmasq.d/*
#        chmod u+rwx,g+rx,o+r /usr/lib/ecss/githome/dnsmasq.d/*

        Set_DB_Connection_config

        COOKIE_FILE=/home/${USER}/.erlang.cookie

        echo "Checking erlang distribution cookie..."
        if ! [[ -f "${COOKIE_FILE}" ]]; then
          echo "Initializing secure erlang distribution cookie..."
          dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 0 > ${COOKIE_FILE}
          chown ${USER}:${GROUP} ${COOKIE_FILE}
          chmod 0400 ${COOKIE_FILE}
        fi
    ;;
    abort-upgrade|abort-deconfigure|abort-remove)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
