#!/bin/bash

. /usr/share/debconf/confmodule

echo "${0} called with: ${*}"

case "${1}" in
remove)
	rm -rf /opt/githome
	rm -rf /var/lib/githome
	rm -rf /usr/lib/githome
	;;
purge)
    echo "Deleting githome user"
    userdel --remove --force githome || true
    echo "User githome deleted"
    rm -rf /etc/githome
    ;;
*)
    echo "postrm called with: ${1}"
    ;;
esac
		