#!/bin/bash

. /usr/share/debconf/confmodule

echo "${0} called with: ${*}"

case "${1}" in
remove)
	rm -rf /opt/githome
	rm -rf /var/lib/githome
	rm -rf /usr/lib/githome
	;;
purge)
    rm -rf /etc/githome
    # userdel --remove-home --system --force githome || true
    # echo"User githome deleted"
    ;;
*)
    echo "postrm called with: ${1}"
    ;;
esac
		